apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: postgrest
  namespace: <project>
  labels:
    cloud.googleapis.com/location: <region>
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: <user_email>
    serving.knative.dev/lastModifier: <user_email>
    client.knative.dev/user-image: eu.gcr.io/<project>/postgrest
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: postgrest-00003-vik
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: <project>:<region>:postgrest
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: <project>-compute@developer.gserviceaccount.com
      containers:
      - image: eu.gcr.io/<project>/postgrest
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: PGRST_DB_URI
          value: postgres://postgres:$DB_PASSWORD@/postgres?host=/cloudsql/<project>:<region>:postgrest
        - name: PGRST_DB_SCHEMA
          value: public
        - name: PGRST_DB_ANON_ROLE
          value: postgres
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true